[package]
name = "rinites"
version = "0.1.0"
authors = ["csrene <renecoutoesilva@gmail.com>"]
edition = "2018"
default-run = "rinites_udp"

[dependencies]
base64 = "0.2.1"
structopt = "0.3"
tokio = "0.1.x"
bytes = "0.4"